from fastapi import APIRouter
from backend.db.db_utils import SessionDep
from backend.crud.f1session import get_sessions_from_meeting_key, get_session_result

router = APIRouter()

@router.get("/sessions/{meeting_key}",
            summary="Gets sessions",
            description="Accesses de DB and fetches all sessions that happened in a given event."
                        "meeting_key is an Integer generated by OpenF1 that connects a F1 to everything that pertains it."
)
def read_sessions(meeting_key: int, session: SessionDep):
    return get_sessions_from_meeting_key(session, meeting_key)

@router.get("/session_result/{session_key}")
def read_session_result(session_key:int, session: SessionDep):
    return get_session_result(session, session_key)
